# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.

<!-- markdownlint-disable -->

"""
# https://keats.github.io/tera/docs/#introduction
body = """
{% if version -%}
  ## [{{ version | trim_start_matches(pat="v") }}] _{{ timestamp | date(format="%Y-%m-%d") }}_

{% else -%}
  ## [unreleased]

{% endif -%}
{% for group, commits in commits | group_by(attribute="group") -%}
    ### {{ group | striptags | trim | upper_first }}

    {% for commit in commits -%}
        -   {% if commit.scope %}_({{ commit.scope }})_ {% endif -%}
            {% if commit.breaking %}[**breaking**] {% endif -%}
            {{ commit.message | upper_first }}
    {% endfor %}
{% endfor -%}
{% if github.contributors -%}\
    ### Contributors

    {% for contributor in github.contributors -%}\
        {% if not contributor.username or contributor.username is ending_with("[bot]") %}{% continue %}{% endif -%}
        -   @{{ contributor.username }}
    {% endfor %}
{% endif -%}
"""
footer = """
<!-- generated by git-cliff on {{ now() | date(format="%Y-%m-%d") }}-->
"""
trim = true
postprocessors = []
output = "CHANGELOG.md"

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = [
  # Remove the PR number added by GitHub when merging PR in UI
  { pattern = '\s*\(#([0-9]+)\)', replace = "" },
  # Check spelling of the commit with https://github.com/crate-ci/typos
  { pattern = ".*", replace_command = "typos --write-changes -" },
]
commit_parsers = [
  # Skip dependency-only chore/fix commits (e.g. from Renovate)
  { message = "^(chore|fix)\\(deps.*\\)", skip = true },
  # Group commits by type
  { group = "<!-- 00 -->🚀 Features", message = "^feat" },
  { group = "<!-- 01 -->🐛 Bug Fixes", message = "^fix" },
  { group = "<!-- 50 -->🚜 Refactor", message = "^refactor" },
  { group = "<!-- 51 -->⚡ Performance", message = "^perf" },
  { group = "<!-- 52 -->🎨 Styling", message = "^style" },
  { group = "<!-- 60 -->📚 Documentation", message = "^docs?" },
  { group = "<!-- 80 -->🧪 Testing", message = "^test" },
  { group = "<!-- 98 -->◀️ Revert", message = "^revert" },
  { group = "<!-- 99 -->⚙️ Miscellaneous Tasks", message = "^chore" },
  { group = "<!-- 99 -->⚙️ Miscellaneous Tasks", message = ".*" },
]
filter_commits = false
topo_order = false
sort_commits = "oldest"

[remote.github]
owner = "JP-Ellis"
repo = "rust-skiplist"
