# release-plz configuration file
# See: https://release-plz.dev/docs/config
[workspace]
# Changelog
changelog_config = "cliff.toml"
changelog_update = true

# Release/publish
git_release_enable = true
publish = true
publish_allow_dirty = false

# Pull Request
pr_draft = true
